### ISSUE TITLE
accessing reader.result in FileReader's onload handler causes crash

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#15]
in frameworker.js, around line #201, we directly assign to the frame's contentWindow, like this:

```
    frame.contentWindow.onoffline = function() {
      if (sandbox.onoffline) sandbox.onoffline();
    };
```

This causes a crash in Nightly.

```
*** Compartment mismatch 0x1067d6000 vs. 0x114047000
Assertion failure: compartment mismatched, at /Users/anant/Code/alder/js/src/jscntxtinlines.h:156
Segmentation fault: 11
```

**Comment by mhammond** [comment]
FWIW, the crash is certainly delivering the FileReader's onload() event for me.  If I change:

```
  reader.onload = function() {
```

to
      reader.xxxxxonload = function() {

It starts file, and I can enter and leave offline mode without a crash and with the console reflecting the handlers are called correctly.  However, with onload being assigned normally I see a crash while loading:

**\* Compartment mismatch 07451FC8 vs. 04C03180
Assertion failure: compartment mismatched, at o:\src\mm\mozilla-hg\mozilla-central\js\src\jscntxtinlines.h:156

I've made a few unsuccessful attempts at injecting the FileReader differently.  FWIW, FileReader isn't currently "injected" at all - it is inherited from the iframe's window object due to the way we create the sandbox.

**Comment by mixedpuppy** [comment]
if i recall the conversation, it is accessing the arraybuffer that causes the crash

**Comment by mhammond** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=738535

**Comment by mhammond** [comment]
Checked into mozilla-central on 2012-03-25 so new nightlies should have it fixed.
